// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC9orFqlncOFJNpQ4G3tedZYrr2pdUuz5M',
    appId: '1:368624307662:web:f9e75e1af6d806ff23af9f',
    messagingSenderId: '368624307662',
    projectId: 'personal-health-tracker-48bb8',
    authDomain: 'personal-health-tracker-48bb8.firebaseapp.com',
    storageBucket: 'personal-health-tracker-48bb8.firebasestorage.app',
    measurementId: 'G-T3FEQT530X',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCrZrX7P81c6HCLCHxWP66sCifTpVpbJgU',
    appId: '1:368624307662:android:05c106ee0201096923af9f',
    messagingSenderId: '368624307662',
    projectId: 'personal-health-tracker-48bb8',
    storageBucket: 'personal-health-tracker-48bb8.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC3EptGD7D7bagbyBL3zzYdDYiDl5UZkdY',
    appId: '1:368624307662:ios:0ceb1752b39dc47b23af9f',
    messagingSenderId: '368624307662',
    projectId: 'personal-health-tracker-48bb8',
    storageBucket: 'personal-health-tracker-48bb8.firebasestorage.app',
    iosBundleId: 'com.example.personalHealthTracker',
  );
}
